// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateSession implements createSession operation.
	//
	// Create Session.
	//
	// POST /sessions
	CreateSession(ctx context.Context, req *CreateSessionRequestSchema) (CreateSessionRes, error)
	// SubmitPassword implements submitPassword operation.
	//
	// Submit Password.
	//
	// POST /passwords
	SubmitPassword(ctx context.Context, req *SubmitPasswordRequestSchema) (SubmitPasswordRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
